// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CSETWebCore.DataLayer.Model
{
    public partial class DOCUMENT_ANSWERS
    {
        /// <summary>
        /// The Document Id is used to
        /// </summary>
        [Key]
        public int Document_Id { get; set; }
        [Key]
        public int Answer_Id { get; set; }
        /// <summary>
        /// The Title is used to
        /// </summary>
        [StringLength(3990)]
        public string Document_Title { get; set; }
        [ForeignKey("Answer_Id")]
        [InverseProperty("DOCUMENT_ANSWERS")]
        public virtual ANSWER Answer { get; set; }
        [ForeignKey("Document_Id")]
        [InverseProperty("DOCUMENT_ANSWERS")]
        public virtual DOCUMENT_FILE Document { get; set; }
    }
}